import { App, Alert, Button, Card, Form, Input, List, Modal, Skeleton, Tag, Typography } from 'antd'
import { PlusOutlined } from '@ant-design/icons'
import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router'
import { createDeviceActivationCodeApi, getRedemptionDevicesApi, revokeRedemptionDeviceApi } from '../api/redemptionApi'
import styles from '../../vouchers/pages/VoucherPages.module.css'

export function OwnerDevicesPage() {
  const { locationId } = useParams(); const { message, modal } = App.useApp(); const [form] = Form.useForm()
  const [devices, setDevices] = useState([]); const [loading, setLoading] = useState(true); const [createOpen, setCreateOpen] = useState(false); const [activation, setActivation] = useState(null); const [errorMessage, setErrorMessage] = useState('')
  const load = useCallback(async () => { setLoading(true); try { setDevices(await getRedemptionDevicesApi(locationId)); setErrorMessage('') } catch (error) { setErrorMessage(error.response?.data?.message ?? 'Không thể tải thiết bị quầy.') } finally { setLoading(false) } }, [locationId])
  useEffect(() => { Promise.resolve().then(load) }, [load])
  async function createCode() { const values = await form.validateFields(); try { setActivation(await createDeviceActivationCodeApi(locationId, values.name)); form.resetFields() } catch (error) { setErrorMessage(error.response?.data?.message ?? 'Không thể tạo Activation Code.') } }
  function revoke(device) { modal.confirm({ title: `Thu hồi thiết bị “${device.name}”?`, content: 'Thiết bị sẽ bị chặn ngay ở request tiếp theo.', okText: 'Thu hồi', okButtonProps: { danger: true }, onOk: async () => { await revokeRedemptionDeviceApi(locationId, device.id); message.success('Đã thu hồi thiết bị.'); await load() } }) }
  return <main className={styles.page}><header className={styles.hero}><div><span className={styles.eyebrow}>Voucher Operator</span><Typography.Title level={2}>Thiết bị quầy</Typography.Title><p>Thiết bị chỉ nhận capability voucher:redeem cho đúng một Location.</p></div><div className={styles.actions}><Link to={`/business/locations/${locationId}/vouchers`}><Button>Quản lý Voucher</Button></Link><Button type="primary" icon={<PlusOutlined />} onClick={() => { setCreateOpen(true); setActivation(null) }}>Kích hoạt thiết bị mới</Button></div></header>{errorMessage ? <Alert type="error" showIcon message={errorMessage} /> : null}{loading ? <Skeleton active /> : <List dataSource={devices} locale={{ emptyText: 'Chưa có thiết bị quầy.' }} renderItem={(device) => <Card style={{ marginBottom: 12, width: '100%' }}><List.Item actions={device.status === 'active' ? [<Button key="revoke" danger onClick={() => revoke(device)}>Thu hồi</Button>] : []}><List.Item.Meta title={<>{device.name} <Tag color={device.status === 'active' ? 'success' : 'default'}>{device.status}</Tag></>} description={`Kích hoạt ${new Date(device.activatedAt).toLocaleString('vi-VN')} · Hoạt động gần nhất ${new Date(device.lastSeenAt).toLocaleString('vi-VN')}`} /></List.Item></Card>} />}<Modal title="Kích hoạt thiết bị mới" open={createOpen} footer={null} onCancel={() => setCreateOpen(false)}>{activation ? <div style={{ display: 'grid', gap: 12, textAlign: 'center' }}><Alert type="warning" showIcon message="Mã chỉ hiển thị một lần và hết hạn sau 10 phút." /><Typography.Title level={2} copyable>{activation.activationCode}</Typography.Title><p>Mở <strong>/redeem/setup</strong> trên thiết bị quầy và nhập mã này.</p><Button onClick={() => setCreateOpen(false)}>Đóng</Button></div> : <Form form={form} layout="vertical"><Form.Item name="name" label="Tên gợi nhớ" rules={[{ required: true, whitespace: true, min: 2, max: 100 }]}><Input placeholder="Ví dụ: Máy quầy chính" /></Form.Item><Button type="primary" block onClick={createCode}>Tạo Activation Code</Button></Form>}</Modal></main>
}
